import type { Command } from 'commander';
import { registerConfigCommand } from './commands/config.js';
import { registerInitCommand } from './commands/init.js';
import { registerDraftCommand } from './commands/draft.js';
import { registerSpecCommand } from './commands/spec.js';
import { registerHookCommand } from './commands/hook.js';
import { registerBuildCommand } from './commands/build.js';
import { registerDoneCommand } from './commands/done.js';
import { registerBlockCommand } from './commands/block.js';
import { registerNeedsContextCommand } from './commands/needs-context.js';
import { registerSettleCommand } from './commands/settle.js';
import { registerProgressCommand } from './commands/progress.js';
import { registerStatusCommand } from './commands/status.js';
import { registerRecommendationCommand } from './commands/recommendation.js';
import { registerInspectCommand } from './commands/inspect.js';
import { registerRecommendCommand } from './commands/recommend.js';
import { registerMilestoneCommand } from './commands/milestone.js';
import { registerContextCommand } from './commands/context.js';
import { registerHandoffCommand } from './commands/handoff.js';
import { registerResumeCommand } from './commands/resume.js';
import { registerAssumptionCommand } from './commands/assumption.js';
import { registerDecisionCommand } from './commands/decision.js';
import { registerIntelligenceCommand } from './commands/intelligence.js';
import { registerDoctorCommand } from './commands/doctor.js';
import { registerMcpCommand } from './commands/mcp.js';
import { registerTutorialCommand } from './commands/tutorial.js';

export function registerAllCommands(program: Command): void {
  registerConfigCommand(program);
  registerInitCommand(program);
  registerDraftCommand(program);
  registerSpecCommand(program);
  registerHookCommand(program);
  registerBuildCommand(program);
  registerDoneCommand(program);
  registerBlockCommand(program);
  registerNeedsContextCommand(program);
  registerSettleCommand(program);
  registerProgressCommand(program);
  registerStatusCommand(program);
  registerRecommendationCommand(program);
  registerInspectCommand(program);
  registerRecommendCommand(program);
  registerMilestoneCommand(program);
  registerContextCommand(program);
  registerHandoffCommand(program);
  registerResumeCommand(program);
  registerAssumptionCommand(program);
  registerDecisionCommand(program);
  registerIntelligenceCommand(program);
  registerDoctorCommand(program);
  registerMcpCommand(program);
  registerTutorialCommand(program);
}
